### ISSUE TITLE
Site not useable on iPhone

### ISSUE THREAD

**Issue by nezda** [gengoai/gengoai.github.io#1]
Site https://www.gengoai.com/  not useable on iPhone  
![52735D2A-76B8-4D19-BFCB-38F58104E3E0](https://user-images.githubusercontent.com/179091/81935671-a3a04e80-95b6-11ea-8aca-ce0ccf8453a0.png)

**Comment by gengoai** [comment]
Think I have modified it to be more phone friendly. Please let me know if it doesn't fix it for you.

**Comment by nezda** [comment]
Much better. Hermes docs are so nice!

**Comment by gengoai** [comment]
Thanks! Creating documentation sucks, but it is useful. I am hoping to start soon on documentation for Apollo and Mango. Let me know if you use Hermes and think anything is missing.
