### ISSUE TITLE
Consider mentioning / linking to github on the landing page

### ISSUE THREAD

**Issue by nezda** [gengoai/gengoai.github.io#2]
People shy away from links that look like 

![image](https://user-images.githubusercontent.com/179091/81940337-1c0a0e00-95bd-11ea-976f-e407257dda5e.png)

Maybe call that Sources or add a Sources link to https://github.com/gengoai/hermes

Get Started Quickly could link to https://www.gengoai.com/hermes/#_installation or something.

![image](https://user-images.githubusercontent.com/179091/81940818-9f2b6400-95bd-11ea-9293-5c71cb555d7b.png) download.com link doesn't work.

Easy to Customize could link to https://www.gengoai.com/hermes/#extraction maybe?

Scalable could link to https://github.com/gengoai/hermes/blob/master/examples/src/main/java/com/gengoai/hermes/SparkSVOExample.java maybe?

**Comment by gengoai** [comment]
Good catch! Updated per your suggestions.
